apiVersion: humanitec.io/v1alpha1
kind: Workload
metadata:
  annotations:
    app.humanitec.io/deployment: 1767e50df7b1a57e
  creationTimestamp: null
  labels:
    app.humanitec.io/app-id: test-03
    app.humanitec.io/env-id: gitops
    app.humanitec.io/org-id: gitops-demo
  name: test-03
spec:
  dependsOnResources:
  - resource-f4990b6059142cf8766d66345ba784be2e007ca4
  - resource-22fb150337c28868e435566fb08339ed285d848d
  manifests:
  - apiVersion: v1
    data: {}
    kind: ConfigMap
    metadata:
      labels:
        app.kubernetes.io/instance: test-03
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: test-03
        helm.sh/chart: default-module-1.16.2
      name: test-03-configmap-sample-app
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app.kubernetes.io/instance: test-03
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: test-03
        helm.sh/chart: default-module-1.16.2
      name: test-03
    spec:
      selector:
        matchLabels:
          app.kubernetes.io/instance: test-03
          app.kubernetes.io/name: test-03
      template:
        metadata:
          annotations:
            checksum/config: 2fb181e786425b8c5b3e40e49653a4cc5502ab3815d410f96969bac8cf4300a7
          labels:
            app.kubernetes.io/instance: test-03
            app.kubernetes.io/name: test-03
        spec:
          containers:
          - envFrom:
            - configMapRef:
                name: test-03-configmap-sample-app
            image: registry.humanitec.io/public/sample-app:1.3.0
            name: sample-app
            resources:
              limits:
                cpu: "0.250"
                memory: 256Mi
              requests:
                cpu: "0.025"
                memory: 64Mi
          imagePullSecrets: []
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app.kubernetes.io/instance: test-03
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: test-03
        helm.sh/chart: default-module-1.16.2
      name: test-03
    spec:
      ports:
      - name: port-default
        port: 8080
        protocol: TCP
      selector:
        app.kubernetes.io/instance: test-03
        app.kubernetes.io/name: test-03
      type: ClusterIP
status: {}
