apiVersion: humanitec.io/v1alpha1
kind: Resource
metadata:
  annotations:
    app.humanitec.io/definition-id: default-humanitec-ingress
    app.humanitec.io/deployment: 1765b0f824ca7b82
    app.humanitec.io/matching-criteria-id: 9c92a2d495b2258e
  creationTimestamp: null
  labels:
    app.humanitec.io/app-id: test-01
    app.humanitec.io/env-id: gitops
    app.humanitec.io/org-id: gitops-demo
  name: resource-8f14839eb5f4b2bc80ce1f3889934b9d86531bec
spec:
  configMapName: resource-configmap-8f14839eb5f4b2bc80ce1f3889934b9d86531bec
  dependsOn:
  - resource-ee3254ff93d9933f96f1729fe09cd17d4364de5a
  - resource-978a2d2cd9ce940facb18750d7b0886a2452a123
  driver: https://drivers.humanitec.io/ingress
  driverInputs:
    driver:
      secrets: {}
      values:
        class: nginx
    resource:
      host: ${resources.dns.outputs.host}
      namespace: test-01-gitops
      rules:
        http:
          /:
            name: sample-app
            port: 8080
            type: prefix
      tls_secret_name: ${resources.tls-cert.outputs.tls_secret_name}
  driverType: humanitec/ingress
  guresid: 8f14839eb5f4b2bc80ce1f3889934b9d86531bec
  id: modules.sample-app.externals.dns
  secretName: resource-secret-8f14839eb5f4b2bc80ce1f3889934b9d86531bec
  secretStoreConfigRef:
    name: gcp-secret-manager-store
    namespace: ""
  type: ingress
  workloadPatchName: resource-patch-8f14839eb5f4b2bc80ce1f3889934b9d86531bec
status: {}
