apiVersion: humanitec.io/v1alpha1
kind: Resource
metadata:
  annotations:
    app.humanitec.io/definition-id: default-humanitec-workload-res
    app.humanitec.io/deployment: 1764f3022d298c18
    app.humanitec.io/matching-criteria-id: db70c377f7134da2
  creationTimestamp: null
  labels:
    app.humanitec.io/app-id: test-01
    app.humanitec.io/env-id: gitops
    app.humanitec.io/org-id: gitops-demo
  name: resource-504e823a1fa2564212084243dd24a1dd017d3e4b
spec:
  configMapName: resource-configmap-504e823a1fa2564212084243dd24a1dd017d3e4b
  dependsOn: []
  driver: builtin://template
  driverInputs:
    driver:
      secrets: {}
      values: {}
    resource:
      id: sample-app
      profile: humanitec/default-module
      spec:
        containers:
          sample-app:
            files: {}
            image: registry.humanitec.io/public/sample-app:1.3.0
            resources:
              limits:
                cpu: "0.250"
                memory: 256Mi
              requests:
                cpu: "0.025"
                memory: 64Mi
            variables:
              HELLO: world
            volume_mounts: {}
  driverType: humanitec/template
  guresid: 504e823a1fa2564212084243dd24a1dd017d3e4b
  id: modules.sample-app
  secretName: resource-secret-504e823a1fa2564212084243dd24a1dd017d3e4b
  secretStoreConfigRef:
    name: gcp-secret-manager-store
    namespace: ""
  type: workload
  workloadPatchName: resource-patch-504e823a1fa2564212084243dd24a1dd017d3e4b
status: {}
