apiVersion: humanitec.io/v1alpha1
kind: Workload
metadata:
  annotations:
    app.humanitec.io/deployment: 1767e510f629505f
  creationTimestamp: null
  labels:
    app.humanitec.io/app-id: test-01
    app.humanitec.io/env-id: gitops
    app.humanitec.io/org-id: gitops-demo
  name: sample-app
spec:
  dependsOnResources:
  - resource-504e823a1fa2564212084243dd24a1dd017d3e4b
  - resource-be03ded52993d8a182eb3757f9571e8e1f808a9c
  manifests:
  - apiVersion: v1
    data:
      HELLO: world
      crazy: var
    kind: ConfigMap
    metadata:
      labels:
        app.kubernetes.io/instance: sample-app
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: sample-app
        helm.sh/chart: default-module-1.16.2
      name: sample-app-configmap-sample-app
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app.kubernetes.io/instance: sample-app
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: sample-app
        helm.sh/chart: default-module-1.16.2
      name: sample-app
    spec:
      selector:
        matchLabels:
          app.kubernetes.io/instance: sample-app
          app.kubernetes.io/name: sample-app
      template:
        metadata:
          annotations:
            checksum/config: e204319bba8457af1ab7f1ad0661e8dcafe76a920d38be33d0fb7dfb389f57f2
          labels:
            app.kubernetes.io/instance: sample-app
            app.kubernetes.io/name: sample-app
        spec:
          containers:
          - envFrom:
            - configMapRef:
                name: sample-app-configmap-sample-app
            image: registry.humanitec.io/public/sample-app:1.3.0
            name: sample-app
            resources:
              limits:
                cpu: "0.250"
                memory: 256Mi
              requests:
                cpu: "0.025"
                memory: 64Mi
          imagePullSecrets: []
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app.kubernetes.io/instance: sample-app
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: sample-app
        helm.sh/chart: default-module-1.16.2
      name: sample-app
    spec:
      ports:
      - name: port-default
        port: 8080
        protocol: TCP
      selector:
        app.kubernetes.io/instance: sample-app
        app.kubernetes.io/name: sample-app
      type: ClusterIP
status: {}
