apiVersion: humanitec.io/v1alpha1
kind: Resource
metadata:
  annotations:
    app.humanitec.io/definition-id: default-humanitec-workload-res
    app.humanitec.io/deployment: 1765b207624668e7
    app.humanitec.io/matching-criteria-id: db70c377f7134da2
  creationTimestamp: null
  labels:
    app.humanitec.io/app-id: test-02
    app.humanitec.io/env-id: gitops
    app.humanitec.io/org-id: gitops-demo
  name: resource-d7930c8a4e42aea509c8c86a33af1cc219a5fa6c
spec:
  configMapName: resource-configmap-d7930c8a4e42aea509c8c86a33af1cc219a5fa6c
  dependsOn: []
  driver: builtin://template
  driverInputs:
    driver:
      secrets: {}
      values: {}
    resource:
      id: test
      profile: humanitec/default-module
      spec:
        containers:
          sample-app:
            files: {}
            image: registry.humanitec.io/public/sample-app:1.3.0
            resources:
              limits:
                cpu: "0.250"
                memory: 256Mi
              requests:
                cpu: "0.025"
                memory: 64Mi
            variables: {}
            volume_mounts: {}
  driverType: humanitec/template
  guresid: d7930c8a4e42aea509c8c86a33af1cc219a5fa6c
  id: modules.test
  secretName: resource-secret-d7930c8a4e42aea509c8c86a33af1cc219a5fa6c
  secretStoreConfigRef:
    name: gcp-secret-manager-store
    namespace: ""
  type: workload
  workloadPatchName: resource-patch-d7930c8a4e42aea509c8c86a33af1cc219a5fa6c
status: {}
