apiVersion: humanitec.io/v1alpha1
kind: WorkloadTemplate
metadata:
  annotations:
    app.humanitec.io/deployment: 1765b207624668e7
  creationTimestamp: null
  labels:
    app.humanitec.io/app-id: test-02
    app.humanitec.io/env-id: gitops
    app.humanitec.io/org-id: gitops-demo
  name: workloadtemplate-test
spec:
  manifests:
  - apiVersion: v1
    data: {}
    kind: ConfigMap
    metadata:
      labels:
        app.kubernetes.io/instance: test
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: test
        helm.sh/chart: default-module-1.16.2
      name: test-configmap-sample-app
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app.kubernetes.io/instance: test
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: test
        helm.sh/chart: default-module-1.16.2
      name: test
    spec:
      selector:
        matchLabels:
          app.kubernetes.io/instance: test
          app.kubernetes.io/name: test
      template:
        metadata:
          annotations:
            checksum/config: c04fbd69af31a321b76cf9944ddeba5146f035133e4513e18d76c7c48c09ecae
          labels:
            app.kubernetes.io/instance: test
            app.kubernetes.io/name: test
        spec:
          containers:
          - envFrom:
            - configMapRef:
                name: test-configmap-sample-app
            image: registry.humanitec.io/public/sample-app:1.3.0
            name: sample-app
            resources:
              limits:
                cpu: "0.250"
                memory: 256Mi
              requests:
                cpu: "0.025"
                memory: 64Mi
          imagePullSecrets: []
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app.kubernetes.io/instance: test
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: test
        helm.sh/chart: default-module-1.16.2
      name: test
    spec:
      ports:
      - name: port-default
        port: 8080
        protocol: TCP
      selector:
        app.kubernetes.io/instance: test
        app.kubernetes.io/name: test
      type: ClusterIP
